import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.scss";
import "react-querybuilder/dist/query-builder.css";
import RootLayout from "@/components/layouts/RootLayout";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
